dist: bionic

language: php

php:
  - 8.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - cp .env.example .env
  - php laravel/artisan key:generate

script: php vendor/bin/phpunit
