version: '3'
services:

  captcha-rsyslog:
    build:
      context: ./docker-damp/
      dockerfile: ./docker/files/rsyslog.df
    image: zablose-rsyslog:3.11
    container_name: captcha-rsyslog
    ports:
      - '51402:514'
    volumes:
      - ./docker-damp/logs/:/var/log/

  captcha-damp:
    build:
      context: ./docker-damp/
      dockerfile: ./docker/files/damp.df
      args:
        - ARG_DB_NAME=${ZDAMP_DB_NAME:-laravel}
        - ARG_DB_PASSWORD=${ZDAMP_DB_PASSWORD}
        - ARG_DB_USER=${ZDAMP_DB_USER:-laravel}
        - ARG_GROUP_ID=${ZDAMP_HOST_GROUP_ID:-1000}
        - ARG_GROUP_NAME=${ZDAMP_HOST_GROUP_NAME}
        - ARG_USER_ID=${ZDAMP_HOST_USER_ID:-1000}
        - ARG_USER_NAME=${ZDAMP_HOST_USER_NAME}
    image: zablose-damp:10.3-php7.4
    container_name: captcha-damp
    ports:
      - '18002:80'
      - '44302:443'
      - '33062:3306'
    extra_hosts:
      - 'captcha.zdev:127.0.0.1'
      - 'www.captcha.zdev:127.0.0.1'
    volumes:
      - ./docker-damp/composer/cache/:/home/${ZDAMP_HOST_USER_NAME}/.composer/cache/
      - ./:/home/web/
    environment:
      - ADD_COMPOSER=true
      - ADD_LARAVEL=false
      - ADD_NODEJS=false
      - APP_ROOT=/home/web/laravel
      - HOST_GROUP_ID=${ZDAMP_HOST_GROUP_ID:-1000}
      - HOST_USER_ID=${ZDAMP_HOST_USER_ID:-1000}
      - TIMEZONE=Europe/London
      - WEB_DOMAIN=captcha.zdev
      - WEB_ROOT=/home/web/laravel/public
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://127.0.0.1:51402'
        tag: 'docker/zablose-damp'
    depends_on:
      - captcha-rsyslog
