version: '3'
services:

  zablose-captcha-rsyslog:
    build:
      context: ./docker-damp/
      dockerfile: ./docker/files/rsyslog.df
    image: zablose-rsyslog:3.11
    container_name: zablose-captcha-rsyslog
    ports:
      - '51400:514'
    volumes:
      - ./docker-damp/logs/:/var/log/

  zablose-captcha-damp:
    build:
      context: ./docker-damp/
      dockerfile: ./docker/files/damp.df
      args:
        - ARG_DB_NAME=${ZDAMP_DB_NAME:-laravel}
        - ARG_DB_PASSWORD=${ZDAMP_DB_PASSWORD:-qwerty}
        - ARG_DB_USER=${ZDAMP_DB_USER:-laravel}
        - ARG_DOMAIN=${ZDAMP_DOMAIN:-captcha.zdev}
        - ARG_GROUP_ID=${ZDAMP_HOST_GROUP_ID:-1000}
        - ARG_GROUP_NAME=${ZDAMP_HOST_GROUP_NAME}
        - ARG_TIMEZONE=${ZDAMP_TIMEZONE:-Europe/London}
        - ARG_USER_ID=${ZDAMP_HOST_USER_ID:-1000}
        - ARG_USER_NAME=${ZDAMP_HOST_USER_NAME}
        - ARG_WEB_ROOT=/home/web/laravel/public
    image: zablose-damp:10.3-php7.4
    container_name: zablose-captcha-damp
    ports:
      - '18000:80'
      - '44300:443'
      - '33060:3306'
    extra_hosts:
      - 'captcha.zdev:127.0.0.1'
      - 'www.captcha.zdev:127.0.0.1'
    volumes:
      - ./docker-damp/composer/cache/:/home/${ZDAMP_HOST_USER_NAME}/.composer/cache/
      - ./:/home/web/
    environment:
      - APP_ROOT=/home/web/laravel
      - HOST_USER_ID=${ZDAMP_HOST_USER_ID:-1000}
      - HOST_GROUP_ID=${ZDAMP_HOST_GROUP_ID:-1000}
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://127.0.0.1:51400'
        tag: 'docker/zablose-damp'
    depends_on:
      - zablose-captcha-rsyslog
