version: '3'
services:

  captcha-rsyslog:
    build:
      context: ./docker-damp/
      dockerfile: ./docker/files/rsyslog.df
    image: zablose-rsyslog:3.11
    container_name: captcha-rsyslog
    ports:
      - '${DAMP_PORT_SYSLOG}:514'
    volumes:
      - ./docker-damp/logs/:/var/log/

  captcha-damp:
    build:
      context: ./docker-damp/
      dockerfile: ./docker/files/damp.df
      args:
        - ARG_DAMP_LOG=${DAMP_LOG}
        - ARG_USER_GROUP_ID=${DAMP_USER_GROUP_ID}
        - ARG_USER_GROUP_NAME=${DAMP_USER_GROUP_NAME}
        - ARG_USER_ID=${DAMP_USER_ID}
        - ARG_USER_NAME=${DAMP_USER_NAME}
        - ARG_WEB_DIR=${DAMP_WEB_DIR}
    image: zablose-damp:10.8-php8.0
    container_name: captcha-damp
    ports:
      - '${DAMP_PORT_HTTP}:80'
      - '${DAMP_PORT_HTTPS}:443'
      - '${DAMP_PORT_DB}:3306'
    extra_hosts:
      - '${DAMP_WEB_DOMAIN}:127.0.0.1'
      - 'www.${DAMP_WEB_DOMAIN}:127.0.0.1'
    volumes:
      - ./.env:/home/${DAMP_USER_NAME}/.env
      - $HOME/.composer/cache/:/home/${DAMP_USER_NAME}/.composer/cache/
      - ./:${DAMP_WEB_DIR}/
      - ./post-setup.sh:/home/${DAMP_USER_NAME}/post-setup.sh
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://127.0.0.1:${DAMP_PORT_SYSLOG}'
        tag: 'docker/zablose-damp'
    depends_on:
      - captcha-rsyslog
